### ISSUE TITLE
onTap or onLongPress methods for removing messages

### ISSUE THREAD

**Issue by GregPuccio** [flyerhq/flutter_chat_ui#13]
Right now nothing happens if you click/long press on a regular message.
Would it be possible to expose the builder for the messages or just the onTap/onLongPress method that we can allow for user options like removing messages or replying to messages (maybe this one would be a swipe feature though?)

Thanks for this great package! Set up was super simple and it's a really beautiful UI.

**Comment by demchenkoalex** [comment]
Hi @GregPuccio thanks for the feedback! :) We do have plans to create a swipe to reply feature, however it might take some time because of a stuff we're working on right now and a regular job. On message long press we planned to create a popup menu with options to delete, copy etc. but again time is the problem. Do you think callbacks will be enough right now for your use case?

**Comment by GregPuccio** [comment]
I think those would be perfect!
Thanks for the quick response and also again for the package!

**Comment by demchenkoalex** [comment]
Released in [v1.0.2](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.0.2) 🙂

**Comment by leferrad** [comment]
Hi guys, does someone have an example of how to use `onMessageLongPress` to delete a message? I really tried different ways, but all of them involved many changes in the way to display the chat or the bubbles, so I don't feel this method allow a natural way to handle simple actions like removing a specific message.
