### ISSUE TITLE
Sent status icon missing

### ISSUE THREAD

**Issue by GrupoDO** [flyerhq/flutter_chat_ui#165]
Hello!

There are five possible status for each message (sending, sent, delivered, seen and error) but only four icons for status (seenIcon, deliveredIcon, sendingIcon and errorIcon). The sentIcon is missing.

Can you add this property? Thank you so much.

Greetings.

Federico

**Comment by demchenkoalex** [comment]
Hello Federico,

Everything is correct. Both delivered and sent statuses use the same deliveredIcon. The difference between those statuses is for a very specific case - push notifications. When message is delivered (e.g. sent to the server) user will see one tick. However, some may want to have a feature that message is delivered, but user didn't get a notification because for example it is late for them. Notify anyway? If you click push is sent and status is sent. But it is still one tick in the UI, since it wasn't yet seen. Of course this is not required and delivered or sent status can just be omitted and you will have images 1:1. Library user controls the data so they free to do whatever suitable for the project.

Best,
Alex
