### ISSUE TITLE
Open at first unread message

### ISSUE THREAD

**Issue by guidocimurro** [flyerhq/flutter_chat_ui#179]
Thank you very much for your precious job!

I'm wondering if it is possible to open the chat at the first unseen message, instead of the more recent one in the chat (at the bottom of it).

Maybe manually set the scroll offset value (ScrollController.initialScrollOffset inside ChatList, but it's internal)?

I tried to view the code and I couldn't manage to find out a solution, but I'm a really amateur and so I'm not sure of myself.

Thank-you very much!

**Comment by invertedpistol** [comment]
There's an option to sort the messages in such a way that the most recent one comes to the top. Is that what you're looking for you?

**Comment by guidocimurro** [comment]
Thank-you invertedpistol, but I would like to open the chat at the first message unread, also it isn't the last one (like Telegram does, I don't remember WhatsApp).

For example, if there are 10 message unread, the ListView should be fixed to the first of these messages, not to the more recent one (the last one).

**Comment by demchenkoalex** [comment]
Hey @guidocimurro sorry for the long response time, had health issues. This is not a straightforward thing to do, because tbh I don't even know how to gracefully handle setting read/seen statuses. Actually statuses right now only reserved for the sender (e.g. person who writes messages).  You can have next statuses when writing:

sending - you pressed send
error - there was an error sending a message
sent/delivered - either the same or if there are push notifications to force notify like in Slack, sent - message is on the server, delivered - push was sent
seen - somebody on the other side has seen the message

speaking of the other side, when I open the chat, how do I determine messages I have seen or not. I guess the easiest solution will be to go through every message before last that I have sent, and mark them all as seen, so they appear as seen for other people. But then I can also stay in the chat after I sent the last message and every new message needs to be marked as seen. Not sure how to handle that. And this is the simple way, if we are talking about nice way like Telegram and others, you would need to scroll to that last message I have seen and again I don't really have the idea, cause messages can be very big and it will require like calculating height of each message and what if there is like a thousand of them... Don't think I can find a solution by myself for this :(

**Comment by guidocimurro** [comment]
Hi demchenkoalex, don't worry for the response time, I really hope that you are fine now!
Thank you for your kindly reply!

**Comment by demchenkoalex** [comment]
No problem! I am better :) would like to start a discussion if anyone has any thoughts about this feature

**Comment by felixgabler** [comment]
Hi, I also think this feature would be great so I'd like to help if I can. 

For the seen message detection: Something one could try for starters would be to use https://pub.dev/packages/visibility_detector on the message widgets to detect once they have been 'seen' and see how it behaves performance wise. This would take care of new messages coming in too.

For the scroll to first unseen: there are also plenty of libraries for scrolling to specific indices in lists (e.g. https://pub.dev/packages/scroll_to_index). One could take a look at how they are doing it.

**Comment by demchenkoalex** [comment]
Hi @felixgabler thanks for your suggestions! That first lib looks promising. With the second one (scroll to indices) we might have a problem cause we use custom scroll view with animations and because of that I had to give up tons of useful scroll view libs (like pagination) - they would simply not work with the custom scroll view. Worth giving a try though I guess.

**Comment by felixgabler** [comment]
Sure, I might have a look at how to implement this later this week. In terms of the message detection, would you even want this to be part of the library? With custom message renderers, I think this can already be implemented outside. I'll also give the scrolling a try once I get to it.

**Comment by demchenkoalex** [comment]
If it can be part of the library that's nice I guess - no need to setup additional code. My thinking was to just wrap messages using that lib you mentioned and setting a callback outside - since we are backend agnostic, actual implementation might be different.
