### ISSUE TITLE
feature: user avatar

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#20]
Hey guys. Just discovered your package and appreciate how professional all your material looks.  
Is it possible for us to show a user avatar next to the chat bubble, or how do you tell people apart in group chats?  Also, do you have any interest in “reaction” so that people can “like” a comment?

**Comment by demchenkoalex** [comment]
Hi @m-j-g right now it is not possible to show the avatar, but we will add it soon, we already have design and everything ready for that. It is on our board https://click.flyer.chat/board. Reactions are planned, but later. We will consider prioritizing it if maybe more people will comment here, because we lack a lot of chat features and need to choose what to do next :)

**Comment by m-j-g** [comment]
> Hi @m-j-g right now it is not possible to show the avatar, but we will add it soon, we already have design and everything ready for that. It is on our board https://click.flyer.chat/board. Reactions are planned, but later. We will consider prioritizing it if maybe more people will comment here, because we lack a lot of chat features and need to choose what to do next :)

Cool, thanks for the response.

**Comment by felixgabler** [comment]
This would really be great for us too!

**Comment by Ajay1901** [comment]
Hey, your library is awesome and helping in a great way for our app. But we feel you are lacking a very vital feature... i.e, in groupRooms the message author's name is not there (who sent what). Are you looking forward to implement anytime soon? If yes any sort of ETA you have in mind?

**Comment by demchenkoalex** [comment]
Hi @Ajay1901 yes, I am looking forward to implement it. As you can see in the pagination issue I've been stuck with Flutter animations for over a month now, finding a lot of strange behaviors and issues. This pushed back features delivery a lot :( I work only weekends and I can't tell you it will be delivered on XX of May, but it will be the first thing to do after I finish replacing ListView with SliverAnimatedList and adding pagination to it. I can't also jump on this feature because SliverAnimatedList affected the design and code structure a lot so I better finish it first. Then this, and this feature will probably take up to 1 day because it will be easy to add.

**Comment by Ajay1901** [comment]
Hey, thanks a lot to reply. I wanted to ask if you can guide me roughly on where to make the changes, I'll give it a shot and raise a PR? Also, there's no direct way of sharing videos I think we have types of the message as File, Images, and text.  Do I need to consider video as a part of File only...!

**Comment by demchenkoalex** [comment]
Not in this case unfortunately, because I've revamped chat/message widgets a lot and it will not be possible to merge those together. Good news is that I'm finally satisfied with SliverAnimatedList and hopefully there are no more pitfalls. Will keep updated. 

Yes, video is only File right now, there is a video message implementation on a fork (check opened pull request discussion, after audio message) and I will work on videos after more basic stuff is ready and working.

**Comment by jangruenwaldt** [comment]
I build this myself, its only a temporary workaround until the package has it too, but I could open a PR if someone wants it.

**Comment by demchenkoalex** [comment]
ok @jangruenwaldt thanks! will take a look when I'll get to implement this.

**Comment by dariakhimych** [comment]
🚫 **The issue is closed**. In order to track the progress please see issue #24.
