### ISSUE TITLE
The sender's avatar and name cannot be displayed

### ISSUE THREAD

**Issue by yrjwcharm** [flyerhq/flutter_chat_ui#264]

**Comment by SheriffOladejo** [comment]
After you set the firstName, lastName and imageUrl for the author/user you also need to set showUserNames: true in the Chat widget. Works as of today

**Comment by AdrKacz** [comment]
That's true, @SheriffOladejo ☺️ However, it may be worth precise that there is indeed something quite strange with the *avatar* and *name* (let me know if you have an answer to the following 😁)
If you want only to display the avatar, you have to set to `true` the `show usernames` anyway and set the names to `null`.
Is that expected behaviour, or am I messing up with something? 🤔

**Comment by demchenkoalex** [comment]
Just checked, `showUserNames` and `showUserAvatars` work as expected, I don't get that part about setting something to `null`.

As for the original issue question (I believe it was about **sender**'s username and avatar, well, sender is always the same person authorised in the chat, I would suggest adding a header on top with the avatar and name, we will not be showing sender's avatar/name on every message :)
