### ISSUE TITLE
Feature Request - Send message on Enter key

### ISSUE THREAD

**Issue by jlubeck** [flyerhq/flutter_chat_ui#27]
When using the Chat on a desktop or web environment, it is expected for the message to be sent when hitting the Enter key. Currently it only works by tapping on the send button.

**Comment by dariakhimych** [comment]
@jlubeck Well, it strongly depends on a use case. In our library, we send a message on submit in order to allow users to add multiple lines by pressing 'enter', and at the same time in order to avoid sending one with typo. Which is a good UX practice for both web and mobile platforms. That is the reason why many services do 'alt' + 'enter' shortcut instead: it kills two birds with one stone. Definitely something to explore in the future releases. 😉

**Comment by dariakhimych** [comment]
@jlubeck I am sure they allow to choose the type of shortcut you find the best for you. In terms of editing messages, we're aware of its importance. So no need for an extra ticket. 😉

**Comment by jlubeck** [comment]
> @jlubeck I am sure they allow to choose the type of shortcut you find the best for you. In terms of editing messages, we're aware of its importance. So no need for an extra ticket. 😉

Giving that option to the devs, and be able to change on runtime (so dev can create a settings page for the user) would be amazing

**Comment by m-j-g** [comment]
Just some extra info into what has already been said.  The expectation from users is going to be that pressing enter sends the message and shift+enter or alt+enter adds a line.  This is how all the major chat platforms work and it feels really weird on web to press enter and it not to send the message.  Can check out Slack, Messages, Whasapp, Facebook Messenger.. I can't find a major chat experience that doesn't send the message on enter, and so it is going to feel really off pressing enter and it not sending.

**Comment by demchenkoalex** [comment]
Released in [v1.1.3](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.3).
