### ISSUE TITLE
Feature Request - Message Actions on Long Press

### ISSUE THREAD

**Issue by jlubeck** [flyerhq/flutter_chat_ui#30]
Would be nice to get extra actions when long pressing a button. Most importantly to be able to reply to other messages, but other options are valid as well. The system could even be made extensible to allow devs to add their own actions

Example:
![IMG_6654](https://user-images.githubusercontent.com/3067603/118998004-188b2e80-b957-11eb-9983-601692498c33.jpg)

**Comment by demchenkoalex** [comment]
Hey @jlubeck we all use Telegram and other chats and we are aware of those features, no need to send a screenshot of every small detail because we will have hundreds of feature requests in one hour. We do this after work on weekends and we have our priorities in a pinned issue right now, later we plan to do milestones specifying every feature planned for a particular milestone. Step by step we will be there.

**Comment by demchenkoalex** [comment]
Ok, makes sense @jlubeck. Then we probably need to use GitHub as our board since we will have all the features here, including milestones. We will try to arrange that this week.
