### ISSUE TITLE
Scroll jumps around when looking at old messages and new ones come in

### ISSUE THREAD

**Issue by jlubeck** [flyerhq/flutter_chat_ui#39]
# General

## What bug do you experience? 🐞
It's not exactly a bug but a UX glitch. When you are in an active chat and scroll up to see older messages, when new messages come in you get some very noticeable jumps in the scroll which can make you lose track of what you were looking at. This could be paired with a recommendation of adding a "scroll to bottom" button (specially when you've gone up quite a bit) 

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
1. Follow documentation to run example project. 
2. Start sending messages into the app and scroll up (while messages are still coming in)

## What behavior is expected? 💡
Smooth scroolling while going up, or holding still while reading an old message. 

# Extras

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: 2.3.0-17.0.pre.130
flutter-chat-ui: 1.0.7

`flutter doctor -v` output 👇

```sh
[✓] Flutter (Channel master, 2.3.0-17.0.pre.130, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.130 at /Users/jan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b95c9915be (26 hours ago), 2021-06-01 16:29:03 -0400
    • Engine revision 84e4b4b5eb
    • Dart version 2.14.0 (build 2.14.0-166.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • iPhone de Jan Lubeck (mobile) • d167f1a8b5eed7cd0312f630a2da37135e6788f3 • ios            • iOS 14.5.1
    • iPad Pro (9.7-inch) (mobile)  • 25E7C8D3-09DE-4A13-84FB-51CEAEBA93C4     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)               • macos                                    • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)                  • chrome                                   • web-javascript • Google Chrome 90.0.4430.212
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): iOS Simulator

OS version (e.g. iOS 14.5, Android 11): iOS 14.5

<br />

**Comment by demchenkoalex** [comment]
Fixed in [v1.1.2](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.2).

**Comment by jlubeck** [comment]
@demchenkoalex I think this issue might have been misunderstood, since the experience now is worse than before.
Looks like now every time that I get a message, the chat scrolls down to the bottom. So on an active chat, there is no way for me to read old messages without getting thrown back to the bottom constantly.

The behavior before this fix was that when I was looking at old messages, it jumped around, but at least you were still NEAR the location of what you were reading. 

If you see how all the other chat apps work, when you scroll up to look at old messages, you as the user control where you are, there is no auto scroll to the bottom, and no jumping around. You do usually also get a button at the bottom right to just scroll back to the bottom. 

Hopefully this was clearer...

**Comment by demchenkoalex** [comment]
When new message is sent, chat will be scrolled to the bottom. This is how Telegram and Facebook Messenger work and there is no reason to do it differently. One problem is that I did it on message received event and forgot that it actually might be incoming message, not sent one, will fix that ASAP.

**Comment by jlubeck** [comment]
Yes, on message sent it's great that it scrolls to bottom. I was talking about received messages. Looking forward to the fix! :D

**Comment by demchenkoalex** [comment]
Regarding incoming messages and being somewhere in the chat history there is no fix. I don't see how it can be done from a library having no control over anything backend related. If we receive a message we add them, it is impossible to have arrays of not rendered messages or something, it will rather break everything else. Unfortunately having some kind of automatic solution may introduce those inconveniences and we will never be on Telegram/Messenger level just because they are apps and not libraries.

**Comment by jlubeck** [comment]
Mmm, I don't think the solution is backend related or to stop adding messages when you are not at the bottom... It's probably something with recalculating the scroll position or something like that when you are not at the bottom... but no worries. I'm more than happy to try to find the solution and then send a PR for you to review. Thanks for the quick replies as always

**Comment by demchenkoalex** [comment]
Fixed scroll to bottom for incoming messages here [v1.1.4](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.4).

As for the jumps in the message history there is no easy fix. If not saving messages to some kind of an array for "future build" while browsing through the history, calculating position is the only option, but

1) The list is animated so the height of the element is dynamic (can assume that this is not the problem because jumps are instant, meaning there is no animation when new element is added while browsing history)
2) We need to calculate the incoming message(s) height(s), since we may have a date divider, message and spacer coming in at the same time, which is not a trivial task + probably will hurt performance badly (calculating size of List elements not visible on the screen, if possible at all)

There is also this issue https://github.com/flutter/flutter/issues/74031 and I don't think that AnimatedList is fully finished and may need to be improved by Flutter team

**Comment by jlubeck** [comment]
Thank you for taking your time to checking this out again. Definitely sounds like a non trivial issue. But it's not unusable so it's not a breaking issue... I'll see if I can figure something out and share if I do. Thanks!

**Comment by Emanuele-n** [comment]
hello everyone, 
any update about this issue?
