### ISSUE TITLE
Why i am getting this error?

### ISSUE THREAD

**Issue by fisforfaheem** [flyerhq/flutter_chat_ui#432]
Running "flutter pub get" in f4zone_2022...
Resolving dependencies...
Because flutter_chat_ui 1.6.6 depends on intl ^0.17.0 and no versions of flutter_chat_ui match >1.6.6 <2.0.0, flutter_chat_ui ^1.6.6 requires intl ^0.17.0.
So, because f4zone_2022 depends on both flutter_chat_ui ^1.6.6 and intl 0.18.1, version solving failed.
pub get failed
command: "/Users/4edoc/Downloads/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/4edoc/Downloads/flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "/Users/4edoc/.pub-cache",
}
exit code: 1

exit code 1

**Comment by idinet-mx** [comment]
I have the same message:

flutter pub get
Running "flutter pub get" in projectmap-app...
Resolving dependencies...
Because flutter_chat_ui >=0.6.0 depends on intl ^0.17.0 and projectmap_app depends on intl ^0.18.0, flutter_chat_ui >=0.6.0 is forbidden.
So, because projectmap_app depends on flutter_chat_ui ^1.6.6, version solving failed.

**Comment by fisforfaheem** [comment]
will the author please update

**Comment by demchenkoalex** [comment]
updated.
