### ISSUE TITLE
please update the stable version on pub.dev and update all depedencies in .yaml file and add full flutter 3.10 support

### ISSUE THREAD

**Issue by fisforfaheem** [flyerhq/flutter_chat_ui#443]
Because flutter_chat_ui 1.6.6 depends on intl ^0.17.0 and no versions of flutter_chat_ui match >1.6.6 <2.0.0, flutter_chat_ui ^1.6.6 requires intl ^0.17.0.

**Comment by nikb7** [comment]
+1

**Comment by HowWhat42** [comment]
I have this problem too.
Please update it

**Comment by stephenhauck** [comment]
+1

**Comment by demchenkoalex** [comment]
Updated.

**Comment by muhleder** [comment]
Still seeing an error here when using flutter_localizations from the sdk. This is on Flutter 3.10.0

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

`Because flutter_chat_ui >=1.6.7 depends on intl ^0.18.1 and every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_chat_ui >=1.6.7 is incompatible with flutter_localizations from sdk.
So, because narrative depends on both flutter_localizations from sdk and flutter_chat_ui 1.6.7, version solving failed.
exit code 1`

**Comment by demchenkoalex** [comment]
Updated.
