### ISSUE TITLE
How can i show the last message?

### ISSUE THREAD

**Issue by schneideralex** [flyerhq/flutter_chat_ui#484]
I wanted to show the last message in the Room Page of every Room.

I have a stream with "FirebaseChatCore.instance.rooms()". 
If a want to get lastMessage of room it is always null. On Firestone Database I can not see a field with "lastMessage". 
But if I try to get a last of lastMessage there is no attribute to get the text.

Here is a example

``` dart
StreamBuilder<List<types.Room>>(
              stream: FirebaseChatCore.instance.rooms(),
              initialData: const [],
              builder: (context, snapshot) {
                if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  return Container(
                    alignment: Alignment.center,
                    margin: const EdgeInsets.only(
                      bottom: 200,
                    ),
                    child: const Text('No Chats'),
                  );
                }

                return ListView.builder(
                  itemCount: snapshot.data!.length,
                  itemBuilder: (context, index) {
                    final room = snapshot.data![index];

                    return GestureDetector(
                        onTap: () {
                          Navigator.of(context).push(
                            MaterialPageRoute(
                              builder: (context) => ChatPage(
                                room: room,
                              ),
                            ),
                          );
                        },
                        child: Card(
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Row(
                              children: [
                                Column(
                                  children: [
                                    CircleAvatar(
                                      radius: 30,
                                      backgroundImage:
                                          AssetImage("assets/images/man.jpg"),
                                    ),
                                  ],
                                ),
                                const SizedBox(
                                  width: 10,
                                ),
                                FutureBuilder<Users>(
                                    future: getUserName(room).first,
                                    builder: (context, snapshot) {
                                      if (snapshot.hasData) {
                                        final user = snapshot.data!;
                                        return Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Text(user.displayName),
                                            Text(room.metadata!['name'],
                                                style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight:
                                                        FontWeight.bold)),
                                            Text(room.lastMessages.last.id.toString()) // <----- Here I want to show the last message of this room.
                                          ],
                                        );
                                      } else {
                                        return Text('No Data');
                                      }
                                    })
                              ],
                            ),
                          ),
                        ));
                  },
                );
              },
            ),

```

**Comment by demchenkoalex** [comment]
Hi!

This is not done automatically. `List<Message>? lastMessages,` exists in types for developers to utilise it, but obviously, it can't work out of the box, unless we provide like the full ready to use service. What you actually need to do is to have some cloud function that will be updating this property on the room, whenever messages in the room change. I can even see it only containing 1 item, if this is your use case ( we were thinking about this like last 1 page of messages so when you enter the room you already have messages loaded and then you paginate). This all was added for advanced use cases that will require developer's work, it can't be automatic.

Since lastMessages are of the type `Message`, they can be any messages, like in real world, last message can be an image. So on frontend you will need a helper function that will go though all message types you support and either get text from `TextMessage`s or write like "image" or "file" in case of others, like messengers do.

Good luck!

**Comment by schneideralex** [comment]
Thank you for your answer. 

You are right, it's a good point because a Message can be an image or file. So I need to find out this is of type text.

But how could I get all Text Messages from this room? 

I tried to do this with a stream of `FirebaseChatCore.instance.messages(room)` but I can't find something like an attribute `content` or `text. I can see the attribute `type` that can help me to find out the type but how could I find the text?

**Comment by demchenkoalex** [comment]
Yes, you need to type cast message as text message if it's type is text :) then it will show you properties from the text message. No need to use `metadata` for this.

Not sure you can get messages of the room, since room type doesn't provide it (it was done long time ago can't remember the reason now). So the only chance will be setting this `lastMessages` somewhere in a cloud function, that was my plan with this, if I'd do it.

**Comment by schneideralex** [comment]
Thank you, it work with the cast from `Message` to `TextMessage`.
