### ISSUE TITLE
URLs picking up ) at end and link failing

### ISSUE THREAD

**Issue by microcoder-py** [flyerhq/flutter_chat_ui#493]
# General

## What bug do you experience? 🐞
Provide a clear and concise description of what the bug is.
In the messages when I am providing a URL in parentheses, FlyerChat is using the ) at the end of the url as part of the URL causing link to fail 

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Just send any URL to flyerchat message

## What behavior is expected? 💡
Just not having the parentheses at the end of it with suitable regex
<br />

# Extras

## Screenshots or videos 📸
If applicable, add screenshots or videos to help explain your problem.
![flyer](https://github.com/flyerhq/flutter_chat_ui/assets/71311548/a0fbbd52-d2dc-408d-8e2c-1b7ea9984478)

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
// Your snippet here...
```
![flyer](https://github.com/flyerhq/flutter_chat_ui/assets/71311548/a0fbbd52-d2dc-408d-8e2c-1b7ea9984478)

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: ...
flutter-chat-ui: ...

`flutter doctor -v` output 👇

```sh
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): ...

OS version (e.g. iOS 14.5, Android 11): ...

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Thanks. Yeah, we have a regex to parse a link and it will not work in 100% cases. Probably if we change it, some other links will break. I am thinking just removing link preview in general, cause having a regex will not parse a link correctly every time and then link preview also will not work on web due to CORS. I think it will be better to just remove it, and leave it to some 3rd party services like https://www.linkpreview.net
