### ISSUE TITLE
Do not scroll to the bottom of long chat response if the message takes more than full screen height. 

### ISSUE THREAD

**Issue by erluxman** [flyerhq/flutter_chat_ui#547]
## What bug do you experience? 🐞
Chat scrolls to the bottom automatically when a long new chat item is added. 

## How can it be reproduced? 🤔
1. create a function that will add a message with more than 300 words,  50 words every second. Just like how chatgpt prints messages in parts to complete a whole message.

## What behavior is expected? 💡
Not sure if it's standard but I expect the screen not to scroll to the bottom when it receives a long message and I want the chat not to scroll past the beginning of the new message so that I do not have to scroll back to the top to start reading the full message. 

Even if it's not a normal behavior, I tried to find a way to use a scroll controller but wasn't able to as `AutoScrollController` isn't available for users. 

Most probably this is my inability to build this feature in which case it would be a help request.

. <br />

# Extras

## Screenshots or videos 📸

![CleanShot 2024-01-15 at 20 08 55](https://github.com/flyerhq/flutter_chat_ui/assets/6260014/2b167ec4-710d-4e8f-853b-483a794055e1)

![CleanShot 2024-01-15 at 20 18 51@2x](https://github.com/flyerhq/flutter_chat_ui/assets/6260014/f5b2496d-912c-4f08-a91d-c0ab4c0a4e8c)

If applicable, add screenshots or videos to help explain your problem.

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
final msgs = data.msgs
            ..sort((a, b) => (b.createdAt ?? 0).compareTo(a.createdAt ?? 0));
          return Scaffold(
            body: Column(
              children: [
                const KNormalLabelAppBar(label: "Chat"),
                Expanded(
                  child: Chat(
                    messages: msgs,
                    onSendPressed: (types.PartialText text) async {
                      chatStateNotifier.addNewMessage(data, text.text);
                    },
                    user: const types.User(id: "0"),
                  ),
                ),
              ],
            ),
          );
```

<br />

# Environment info
flutter: 3.16.5,
flutter-chat-ui: ^1.6.10

`flutter doctor -v` output 👇

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources
```

<br />

# Platform
iOS simulator. OS version (e.g. iOS 17.0.1): ...
didn't test in android

<br />

**Comment by demchenkoalex** [comment]
Hey! `gpt` mode is something I was looking to add to `v2`, cause it is really something different from a normal chat. Back in the day, when I created this, there was no chat gpt yet. And if you will open any messenger and start texting with somebody, you will expect chat scrolling to the end, otherwise imagine scrolling every time you get a message. This is some old video from `v2` version to illustrate the example. 

https://github.com/flyerhq/flutter_chat_ui/assets/14123304/59bd50fd-f8d6-467b-b404-5bb767b9021e

In case of `gpt` you  don't want it to scroll all the way, but fixed at the beginning of the long message. I think it will be interesting to calculate, not even sure where to start. But for sure this needs to exists alongside current behaviour, and be an option.

**Comment by appinteractive** [comment]
I think it's not just `gpt` but true for all kinds of long messages. If the scroll view is always scrolled to the end, you need to scroll back up, which is not a good user experience. I think there should be a way to control it manually. For example, you may want to only scroll to the first unread message (which most messengers do, I believe) 

So there should be a way to get the position of a specific bubble and then scroll to it.
A solution might be to get the desired item by key and then use the `Scrollable.ensureVisible`.

See: https://diamantidis.github.io/2021/10/10/exploring-flutter-scrollable-ensurevisible

**Comment by demchenkoalex** [comment]
I just sent a very long message to myself in a messenger I use daily (Telegram) and it was scrolled to the very bottom and imo it makes sense (it is a unique case to receive such a long message it won't fit a screen anyway). And it makes sense in `gpt` to stick to the top, because message is being created constantly, not like you get the whole thing right away. 

Scroll to the first unread is a different feature I believe.

Anyway, I think this `gpt` mode (it can be named differently) can work for both cases and try to stick long message to the top, I will be trying different packages to do it, or will ask community for help when `v2` branch will be main.

**Comment by yassinsameh** [comment]
The flow the ChatGPT App follows is:
Step 1) When the response is incoming, It sticks to the bottom as long as the user hasn't scrolled upwards.
Step 2) It only pauses the scroll to bottom once the user has scrolled a bit to the top even if response is still incoming.

Step 1 seems to be working as expected, how can step 2 be implemented? On user up scroll i can detect that and want to provide a way to prevent the scroll to go to the end of the message. Would you know an approach? @demchenkoalex

**Comment by demchenkoalex** [comment]
@yassinsameh needs to be added in package, I don't think it will be possible to override the behaviour from the outside. I am not working on v1 anymore, still blocked with v2 (now doing cross platform cache package, I need it to do the best UI possible) and as soon as v2 is unblocked I will be able to look into different scroll behaviours.

**Comment by demchenkoalex** [comment]
I did example of this in the Gemini example of `v2`.
