### ISSUE TITLE
SendButtonVisibilityMode.editing: send button not added after typing on samsung keyboard

### ISSUE THREAD

**Issue by qeepcologne** [flyerhq/flutter_chat_ui#564]
i am using InputOptions with sendButtonVisibilityMode: SendButtonVisibilityMode.editing (show the button when trimmed text is not empty).
This is working fine with gboard.
But with samsung keyboard, button is not becoming visible after i type some characters (only after i close the keyboard).
I could reproduce this on 2 different devices and when i switch to gboard, everything works fine.
I added onTextChanged and it is called after every character typed with both keyboards.
So, i do not understand why the button is not updated.
This might be a bug in TextEditingController, but even if so, we need a workaround here.

**Comment by levmorgot** [comment]
I faced the same problem on Xiaomi
The button appears after closing the keyboard, or after adding a space

**Comment by demchenkoalex** [comment]
could you try one thing - there is this `textEditingController` that kind of transforms input text with a simple markdown - could you disable it using `inputOptions` and pass Flutter's own `TextEditingController()` to the `textEditingController` option? cause otherwise code is pretty straightforward,`textEditingController.text != ''`

**Comment by demchenkoalex** [comment]
ah so I need to call setState? will keep this in mind for `v2`

**Comment by yevgeniaronov** [comment]
have the same issue on s23 plus with swiftkey (haven't checked other devices)

**Comment by demchenkoalex** [comment]
hiding send button is not a feature anymore in `v2` - it will always be visible.
