### ISSUE TITLE
More complex example for people wanna using this as a product base?

### ISSUE THREAD

**Issue by luohao123** [flyerhq/flutter_chat_ui#60]
Hi, it looks this repo provides a enhancement components for Chat app. It looks beautifull then anyother pakcages I can found in flutter for Chat.

Does there any more complicated example showing how to use it? More specific it should include Session pages (page that includes all history sessions) and the detailed chat page.

**Comment by demchenkoalex** [comment]
Hi @luohao123 thanks for the kind words!

You are looking at backend with this question, this package is a UI and UI only, so it is not possible to have this kind of an example here, however we do another package, https://github.com/flyerhq/flutter_firebase_chat_core which uses Firebase as a backend and chat UI, where you have a screen with rooms and a chat in the example. Keep in mind that even though there is an example with chat rooms, it is not a part of our UI implementation (and we don't plan to do it) because chat screens are in most cases similar, but when it comes to other screens (like list of rooms, users, stories etc) they are mostly different. And it shouldn't be a problem implementing on your own, in the end it is only a list.

**Comment by demchenkoalex** [comment]
Closing due to no response, but I think the answer was given :) feel free to reply.
