### ISSUE TITLE
[Feature Request] Customizable and extendable `MessageType` proposal

### ISSUE THREAD

**Issue by UsamaKarim** [flyerhq/flutter_chat_ui#633]
Hi, I have a design proposal for customisable and extendable message types. There are pros and cons to this design. At first glance it seems to me that it might not be a breaking change.

Origin: It have been derived form the Stackoverflow post when `Enum` was not available in dart language, but there was a workaround available. https://stackoverflow.com/a/15854550/14028477

## Pros
1. It can be `extends`
2. It has similarity to `Enum`
3. It can be used in serialization/deserialization for use in custom model classes and custom name to any type can be given.

## Cons
1. The previous types has to reimplemented in the extended class as static types of parent class are not accessible from subclass instance
2. It seems verbose

## Code Design

```dart

void main() {
  const messageType = MessageType.video;

  switch (messageType) {
    case MessageType.text:
      print('This is a text message type');
    case MessageType.audio:
      print('This is a audio message type');
    case MessageType.video:
      print('This is a video message type');
  }

  const myMessageType = MyMessageTypes.text;

  switch (myMessageType) {
    case MyMessageTypes.text:
      print('This is a text message type');
    case MyMessageTypes.audio:
      print('This is a audio message type');
    case MyMessageTypes.video:
      print('This is a video message type');
    case MyMessageTypes.image:
      print('This is a image message type');
    case MyMessageTypes.poll:
      print('This is a poll message type');
    case MyMessageTypes.location:
      print('This is a location message type');
  }
}

class MessageType {
  const MessageType._internal(this._value);
  final String _value;

  @override
  String toString() => 'Enum.$_value';

  static const text = MessageType._internal('text');
  static const audio = MessageType._internal('audio');
  static const video = MessageType._internal('video');
}

/// Custom Defined Message Types
class MyMessageTypes extends MessageType {
  const MyMessageTypes._internal(super.value) : super._internal();

// Reimplement original types
  static const text = MyMessageTypes._internal('text');
  static const audio = MyMessageTypes._internal('audio');
  static const video = MyMessageTypes._internal('video');

  // More customisable message types
  static const location = MyMessageTypes._internal('location');
  static const image = MyMessageTypes._internal('image');
  static const poll = MyMessageTypes._internal('poll');
}
```

**Comment by demchenkoalex** [comment]
Hello! These are types I created for `v2` - https://github.com/flyerhq/flutter_chat_ui/blob/8807a60be9dcb9da270678a96a1cd366289d8f88/packages/flutter_chat_core/lib/src/models/message.dart (obviously not complete but you get the idea)

I really like the new approach since I don't have to write anything, most stuff is handled by Freezed. I am not sure I will be able to extend it like in your case, but it is definitely working nicely and does not require a lot of code.

My main points with these models are:
- I should have 1 message class, so users can just get array of Message
- Message should have copyWith id available without explicit typing
- There should be a way to check for actual message type (I can do message is TextMessage)
- After you map to the actual message type copyWith specific message fields should be available

does you approach can handle all that? I only see enum but I don't know how it should look fully

**Comment by UsamaKarim** [comment]
My approach had previous message type design in my mind.

The `v2` approach seems good but it has a drawback of not extend able classes, it will force to use `metaData` tag that doesn't seems to be a good approach. I will try if we can do something similar to this

```dart
abstract class MessageType {}

sealed class Message extends MessageType with _$Message {
```

**Comment by demchenkoalex** [comment]
feel free to reopen if you will be able to achieve extensibility and abstract Message structure, but for the ease of use I will stick with current `v2` implementation for now.
