### ISSUE TITLE
how to edit the bottom input chat elements on v2?

### ISSUE THREAD

**Issue by lcsvcn** [flyerhq/flutter_chat_ui#665]
So I want to implement this using this library, basically is a audio feat, similar to WhatsApp. on mobile you can press and hold record audio or press and swipe up to lock, so you can record until you hit send (both showing audio wave like the image below).

https://github.com/user-attachments/assets/4f817730-2add-4bb2-a760-a83e678d31ed

Here is what I have on the V2 version so far:

<img width="271" alt="Screenshot 2024-10-31 at 01 23 07" src="https://github.com/user-attachments/assets/cf8f6e12-fe27-4abc-b1da-51a81341dea3">

So I need to edit it to remove the attach file icon and add the audio icon and the behaviour I explained above. I saw that there is a PR on v1 implementing audio, so I would like to know how can it be done in the new v2 version.

**Comment by demchenkoalex** [comment]
hey!

`Builders` class is an entry to all components customisation. In this case,

```dart
builders: Builders(inputBuilder: (context) => const ChatInput())
```

to build the input. Note that I export all components that I created like `ChatInput`, `ChatMessage` etc. So the code above basically has no effect because it builds the same component it builds inside the chat. 

Next, components like `ChatInput` have params as well, so you can do something like this among other things:

```dart
builders: Builders(
  inputBuilder: (context) => const ChatInput(
    attachmentIcon: null,
  ),
)
```

which will remove attachment icon. That being said I did not add support for widgets on the left and right side yet (probably need to add that), however given you can build anything you can do now:

```dart
builders: Builders(
  inputBuilder: (context) => YourCustomInput(),
)
```

and you can totally copy `ChatInput` from the source code and remove everything you don't need and add anything you need. This should allow you to do whatever you want. 

Let me know if you have any issues, I am still figuring out the API :)

**Comment by nbonamy** [comment]
For info. here is my custom ChatInput. Microphone button not functioning yet.
https://github.com/nbonamy/witsy-mobile/blob/main/lib/components/chat_input.dart

<img width="440" alt="image" src="https://github.com/user-attachments/assets/47f44e79-193f-4810-a82f-afcf4e76d677">
