### ISSUE TITLE
onEndReached function fired too many times

### ISSUE THREAD

**Issue by infernowalker** [flyerhq/flutter_chat_ui#69]
Hi, when I pull down the chat page to load more message, the onEndReached function is called more than once, shouldn't it only be called one time per pull? or maybe I didn't implement it correctly? It seems that the longer I pull, the function gets called more times.

```
Future<void> _loadMoreMessage() async {
  print('test');
}
```

```
Chat(
  onEndReachedThreshold: 1,
  onEndReached: _loadMoreMessage,
)
```

Anyway this library is really good, thanks for the work!

**Comment by demchenkoalex** [comment]
Hi @infernowalker 

Thanks you!

Of course it is being called many times, it is a developer's job to set requesting state, fire a request, update data source and set requesting to false :) only one request :)

**Comment by UADACID** [comment]
> Hi @infernowalker
> 
> Thanks you!
> 
> Of course it is being called many times, it is a developer's job to set requesting state, fire a request, update data source and set requesting to false :) only one request :)

any example to handle this case ?

**Comment by UADACID** [comment]
> https://docs.flyer.chat/flutter/chat-ui/advanced-usage#pagination

Thanks you! 😆😆😆 @demchenkoalex

**Comment by gtu-myowin** [comment]
Hi @demchenkoalex, I just wanted to be sure. Are you saying to fire `onEndReached` conditionally like this?

```dart
Chat(
	messages: _messages,
	onAttachmentPressed: _handleAtachmentPressed,
	onMessageTap: _handleMessageTap,
	onPreviewDataFetched: _handlePreviewDataFetched,
	onSendPressed: _handleSendPressed,
	showUserAvatars: true,
	showUserNames: true,
	user: _user,
	onEndReached: _isRequesting ? null : _handleEndReached, // I'm talking about this line.
	isLastPage: _isLastPage,
)
```

**Comment by demchenkoalex** [comment]
Hi @gtu-myowin no, function should always be passed, otherwise chat will think there is no pagination. But inside the function, `_handleEndReached`, just don't fetch when `_isRequesting` is true, do an early exit. Chat will be trying to use `_handleEndReached` multiple times, but with the early exit nothing will be happening, and eventually if data will be loaded, `_handleEndReached` won't be triggered, cause new items will appear (will trigger again if you will continue scrolling) and if there will be an error, it will try to re-fetch again on pull.

**Comment by gtu-myowin** [comment]
Thank you for your explanation. I will give it a try.
