### ISSUE TITLE
Support long message history with lazy loading

### ISSUE THREAD

**Issue by petoknm** [flyerhq/flutter_chat_ui#7]
Is there any support for lazy loading history only if user scrolls to the top?
Right now the API needs a full list of messages and there is no callback for fetching more messages afaik.

**Comment by demchenkoalex** [comment]
Hi @petoknm, yes, it's among the first features we plan to add. We also think of creating some kind of an open roadmap so those things are visible to the community.

**Comment by mss30** [comment]
Looking forward for this feature to be implemented.

**Comment by demchenkoalex** [comment]
Hi @mss30 sorry for the delay, I spent like a month already trying to implement beautiful automatic animations with AnimatedList before taking this one, since I noticed all the pagination libraries recreating normal lists, but not animated ones. Want to do it the right way, so it works with animations :)

**Comment by demchenkoalex** [comment]
UPDATE: After I thought that animations are done I got another bunch of unwanted behavior :/ My last option is to use `CustomScrollView` with `SliverAnimatedList` + separating date dividers to their own items, not attaching them to messages. Another round of testing this weekend.

**Comment by jangruenwaldt** [comment]
This feature will be great! So happy to see. Also, love the libary btw, super awesome!

**Comment by dariakhimych** [comment]
🚫 **The issue is closed.** In order to track the progress please see issue #24.
