### ISSUE TITLE
Realtime API

### ISSUE THREAD

**Issue by fabioselau077** [flyerhq/flutter_chat_ui#72]
Hi, thanks for the package, it's wonderful.
I would like to know if there is a way to make the chat realtime with the data returning from the API created in Laravel.
I have already managed to list the messages and add them to the database, but I would like to have the possibility of showing new messages from other users on the screen without having to leave and enter the screen again.
Is it possible to do this with the API in Laravel?

**Comment by demchenkoalex** [comment]
Hi @fabioselau077 this package is UI only and it is backend agnostic so it should work with anything. Unfortunately asking about PHP API here might not be the best idea, because this is a UI repo written in Dart. I guess what you want is to be on the chat screen and see incoming messages in real-time, so we are looking at WebSockets to do so, adding messages to the array when events are coming in. The API design and implementation is completely on your side, can't help with PHP, out of mine field of expertise.

**Comment by fabioselau077** [comment]
> Hi @fabioselau077 this package is UI only and it is backend agnostic so it should work with anything. Unfortunately asking about PHP API here might not be the best idea, because this is a UI repo written in Dart. I guess what you want is to be on the chat screen and see incoming messages in real-time, so we are looking at WebSockets to do so, adding messages to the array when events are coming in. The API design and implementation is completely on your side, can't help with PHP, out of mine field of expertise.

Thanks for the answer.
Another question, can I change the "Message" label that is in the text box?
I wanted to translate into my language.
