### ISSUE TITLE
Admin features: swear word filter, review chat history, report user, block user, flood limit

### ISSUE THREAD

**Issue by giorgio79** [flyerhq/flutter_chat_ui#8]
űAny plans for admin ui and features:
swear word filter

- report user : send an email with chat history and user ids perhaps? Or save a report in firestore, with a chat history so an admin can review?
- review chat history:  in relation to above
- block user: Probably this can be handled outside of this app
- flood limit: limit how many messages a user can send in a time?

**Comment by demchenkoalex** [comment]
Hi @giorgio79 is it related to the UI itself? UI is backend agnostic so it doesn't matter if you use Firebase or whatever service you want to use. Also, we don't handle rendering users in this library (since it is completely different for any other app, e.g. app like Tinder doesn't render users at all) and reporting a user is outside of the scope, you will probably have your own UI for that, you can pass an ID to the report and then as an admin you can review that claim. Everything else is also related to the backend. If you plan to use Firebase, flood limit and swear word filter will probably be done using cloud functions.

**Comment by giorgio79** [comment]
Thanks Alex! Good points :) Closing issue here in the UI repo.
